print("welcome my friends can you pls enter ur fav language")
s={}
name=input("enter your name = ")
lan=input("enter your fav language = ")
s.update({name:lan})
name=input("enter your name = ")
lan=input("enter your fav language =")
s.update({name:lan})
name=input("enter your name = ")
lan=input("enter your fav language =")
s.update({name:lan})
name=input("enter your name = ")
lan=input("enter your fav language =")
s.update({name:lan})
print(s)