fruit=[]
f1=int (input("enter the marks of first = "))
fruit.append(f1)
f2=int (input("enter the marks of first = "))
fruit.append(f2)
f3=int (input("enter the marks of first = "))
fruit.append(f3)
f4=int (input("enter the marks of first = "))
fruit.append(f4)
f5=int (input("enter the marks of first = "))
fruit.append(f5)
f6=int (input("enter the marks of first = "))
fruit.append(f6)
fruit.sort()
print (fruit)