Marks=[]
f1=input("enter the marks of first = ")
Marks.append(f1)
f2=input("enter the marks of first = ")
Marks.append(f2)
f3=input("enter the marks of first = ")
Marks.append(f3)
f4=input("enter the marks of first = ")
Marks.append(f4)
f5=input("enter the marks of first = ")
Marks.append(f5)
f6=input("enter the marks of first = ")
Marks.append(f6)
